server:
  port: ${PAYMENT_SERVICE_PORT:8082}

services:
  product-service:
    base-url: ${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:payment-service;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS public\;SET SCHEMA public
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: public
        format_sql: true
  flyway:
    enabled: true
    schemas: public
    locations: classpath:db/migration-h2
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_payment_service_history

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
