create table public.users (
    id bigint generated by default as identity primary key,
    username varchar(255) unique
);

insert into public.users (username)
select 'test_user_1'
where not exists (
    select 1
    from public.users
    where username = 'test_user_1'
);

insert into public.users (username)
select 'test_user_2'
where not exists (
    select 1
    from public.users
    where username = 'test_user_2'
);

insert into public.users (username)
select 'test_user_3'
where not exists (
    select 1
    from public.users
    where username = 'test_user_3'
);
