feature4.datasource.url=${SUPABASE_DB_URL:jdbc:postgresql://aws-0-eu-west-1.pooler.supabase.com:6543/postgres?sslmode=require}
feature4.datasource.username=${SUPABASE_DB_USERNAME:feature4_app.qdcvoukgdmgntpmathjr}
feature4.datasource.password=${SUPABASE_DB_PASSWORD:}
feature4.datasource.maximum-pool-size=5
feature4.datasource.pool-name=feature4-users-pool
feature4.datasource.prepare-threshold=0
