create table public.products (
    id bigint generated by default as identity primary key,
    account_number varchar(64) not null unique,
    balance numeric(19, 2) not null,
    product_type varchar(32) not null,
    user_id bigint not null,
    constraint products_product_type_check check (product_type in ('ACCOUNT', 'CARD'))
);

create index idx_products_user_id on public.products(user_id);

insert into public.products (account_number, balance, product_type, user_id)
select '40817810000000000001', 15320.45, 'ACCOUNT', u.id
from public.users u
where u.username = 'test_user_1'
  and not exists (
      select 1
      from public.products p
      where p.account_number = '40817810000000000001'
  );

insert into public.products (account_number, balance, product_type, user_id)
select '40817810000000000002', 810.00, 'CARD', u.id
from public.users u
where u.username = 'test_user_1'
  and not exists (
      select 1
      from public.products p
      where p.account_number = '40817810000000000002'
  );

insert into public.products (account_number, balance, product_type, user_id)
select '40817810000000000003', 42000.99, 'ACCOUNT', u.id
from public.users u
where u.username = 'test_user_2'
  and not exists (
      select 1
      from public.products p
      where p.account_number = '40817810000000000003'
  );

insert into public.products (account_number, balance, product_type, user_id)
select '40817810000000000004', 120.50, 'CARD', u.id
from public.users u
where u.username = 'test_user_3'
  and not exists (
      select 1
      from public.products p
      where p.account_number = '40817810000000000004'
  );
